---
- block:
  # - name: Install python-dnf and selinux binding
  #   shell: sudo dnf install python python-dnf libselinux-python -y
  # - name: Install some additional packages
  #   dnf: name={{ item }}
  #   with_items:
  #     - python-firewall
  #     - firewalld
  #     - cockpit
  # - name: Install ntpd
  #   dnf: name=ntp state=present
  # - name: Configure ntpd
  #   service: name=ntpd state=started enabled=yes
  # - hostname: name={{ server_name }}
  # - name: Start firewalld
  #   service: name=firewalld state=started enabled=yes
  # - name: Allow 80/tcp
  #   firewalld: port=80/tcp permanent=true state=enabled
  # - name: Restart firewalld
  #   service: name=firewalld state=reloaded
  - name: Install additional packages
    dnf: name={{ item }} state=present
    with_items:
     - bash-completion
     - couchdb
     - file
     - gcc
     - git
     - libffi-devel
     - libselinux-python
     - libsodium
     - libsodium-devel
     - logrotate
     - nginx
     - npm
     - openssl-devel
     - policycoreutils-python
     - python
     - python-dateutil
     - python-devel
     - python2-systemd
     - python2-systemd
     - redhat-rpm-config
     - redis
     - sqlite-devel
     - systemd-devel
     - tmux
     - zeromq3-devel

  # - name: Install bower
  #   command: npm install -g bower

  # - name: Install bower
  #   command: npm install -g gulp
